version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        restart: unless-stopped
        tty: true
        volumes:
            - ./:/home
        network_mode: 'host'
        ports:
            - "8000:8000"